---
- name: This sets up an httpd webserver
  hosts: group1
  tasks:
  - name: Install apache packages
    yum:
      name: httpd
      state: present
  - name: Start service httpd, if not started
    service:
      name: httpd
      state: started
  - name: example copying file with owner and permissions
    copy:
      src: /etc/ansible/index.html
      dest: /var/www/html/index.html
