---
- name: This sets up an httpd webserver
  hosts: group1
  tasks:
  - name: Install apache packages 
    yum:
      name: httpd
      state: present
  - name: Start service httpd, if not started
    service:
      name: httpd
      state: started
